### ISSUE TITLE
SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by dl-web-dev** [ChurroC/next-server-theme#1]
Appears there is an extra colon being injected that causes this `SyntaxError: Unexpected token ':'` error to be thrown. 

<img width="800" alt="Screenshot 2024-07-11 at 1 19 18 PM" src="https://github.com/ChurroC/next-server-theme/assets/61286551/53dbffc1-765f-4b64-afe9-c8c2b1a23075">

**Comment by ChurroC** [comment]
There was a typo in the script being sent to the client causing an extra colon to be placed.

**Comment by dl-web-dev** [comment]
The Fix for this issue appears to have left in some logging statements in the console! But other than that believe all is good.
